spring:
  redis:
    host: localhost
    port: 6379
    password: your_redis_password
  security:
    oauth2:
      client:
        registration:
         salesforce:
            client-id: Ov23liJuN6b6V3ufArlW
            client-secret: 1622a4e8d03d5837538e845146777274b91f121b
            scope: openid
            authorization-grant-type: client_credentials
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          salesforce:
            authorization-uri: https://login.salesforce.com/services/oauth2/authorize
            token-uri: https://login.salesforce.com/services/oauth2/token
kms:
  provider: AWS # or any other KMS service
  key-id: your_kms_key_id
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  mvc:
     servlet:
      path: /
  servlet:
     context-path: /
springdoc:
   api-dcos:
   path: /api-docs 
spring.ssl.bundle.pem:
  demo:
    reload-on-update: true
    keystore:    
      certificate: "certs/demo.crt"
      private-key: "certs/demo.key"
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: /logs/archived/application-%d{yyyy-MM-dd}.%i.log
      max-history: 30
  file:
   name: /logs/application.log
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %-5level [%thread] %logger : %msg%n"
    level: "%5p"
  level:
    root: DEBUG
